# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 033237e9824b3ee3c17e69a9a8364771f9d17d9843b52eb793221616f3b7d0ec3b66e3aeafeec7e45c529552cad57b10d464ece00b39b7e0a9df4a0b13769915

test:
  secret_key_base: f98d8524212c02dca96c4e3ceee3f0412dfdf5746931b4f44ba35f160a323e8b5163ad5571b68f4d8bc219ef03f9ae7eeb835a3d64ef774f198f39012ee59659

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
